port = 3000
debug = true
domain = "localhost:3000"

[database]
host = "localhost"
port = 5432
database = "manucure"
user = "postgres"
password = "postgres"

[search_engine]
url = "http://localhost:7700"
api_key = "fMuxK9AIppcbb6H08T]gm>YAz"

[oauth_provider]
client_id = "manucure"
client_secret = "xZjWvaWPcHlglqcp5b19iLdke5sf9JG7"
provider = "https://keycloak.cloud.hoohoot.org"
user_info_url = "/auth/realms/hoohoot/protocol/openid-connect/userinfo"
auth_url = "/auth/realms/hoohoot/protocol/openid-connect/auth"
token_url = "/auth/realms/hoohoot/protocol/openid-connect/token"
