port = 3000
debug = true
domain = "localhost:3000"

[database]
host = "localhost"
port = 5432
database = "manucure"
user = "postgres"
password = "postgres"

[search_engine]
url = "http://localhost:7700"
api_key = "a355999865ad9fa5b406eed605344e933324a75629a57e2e41549f6ac25db7d6"
admin_key = "23f9f18e53c4bc3e5690ff67804389ca7af2b13fb49c1b4d0987efda53e9f05e"

[oauth_provider]
client_id = "manucure"
client_secret = "zB6L5Xw2C7ynDTDpWucCj58S71LPeMav"
provider = "https://keycloak.cloud.hoohoot.org"
user_info_url = "/auth/realms/hoohoot/protocol/openid-connect/userinfo"
auth_url = "/auth/realms/hoohoot/protocol/openid-connect/auth"
token_url = "/auth/realms/hoohoot/protocol/openid-connect/token"
