version: "3.9"
services:
  postgres:
    image: docker.io/postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "manucure"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  meilisearch:
    image: getmeili/meilisearch:v1.0
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: fMuxK9AIppcbb6H08T]gm>YAz
    ports:
      - "7700:7700"
    volumes:
      - ./docker/meili_data:/meili_data
